name: flutter_ball_or_bomb
description: A new Flutter animation project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.5
  freezed_annotation:
  shared_preferences: ^2.0.6
  wakelock: ^0.5.2

dev_dependencies:
  build_runner:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed:

flutter:
  uses-material-design: true
